USE iconic_estates_india;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE property_images;
TRUNCATE TABLE floor_plans;
TRUNCATE TABLE properties;
TRUNCATE TABLE builders;
TRUNCATE TABLE civil_engineers;
TRUNCATE TABLE interior_designers;
TRUNCATE TABLE exterior_designers;
TRUNCATE TABLE leads;
TRUNCATE TABLE inquiries;
TRUNCATE TABLE market_reports;
TRUNCATE TABLE testimonials;
TRUNCATE TABLE ownership_journey;
TRUNCATE TABLE iconic_addresses;
TRUNCATE TABLE platform_stats;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO builders (name, logo_url, years_experience, total_projects, cities_served, description, rera_registration) VALUES
('Shivalik Group', '/images/experts/Shivalik_Group.jpeg', 28, 65, 'Ahmedabad,Gandhinagar', 'Gujarat-rooted developer known for premium residential townships and retail destinations.', 'GJ/RERA/SHIV/001'),
('Adani Realty', '/images/experts/Adani_Realty.jpeg', 20, 40, 'Ahmedabad,Mumbai,Gurugram', 'Real estate arm of the Adani Group, delivering large-format mixed-use developments.', 'GJ/RERA/ADNI/002'),
('Godrej Properties', '/images/experts/Godrej_Properties.jpeg', 27, 200, 'Mumbai,Pune,Bangalore,Gurugram', 'One of India\'s most trusted listed developers across residential and commercial assets.', 'MH/RERA/GODR/003'),
('Sobha Limited', '/images/experts/Sobha_Limited.jpeg', 30, 150, 'Bangalore,Gurugram,Pune', 'Engineering-led luxury developer with in-house backward integration.', 'KA/RERA/SOBH/004'),
('Prestige Group', '/images/experts/Prestige_Group.jpeg', 38, 290, 'Bangalore,Hyderabad,Chennai,Mumbai', 'South India\'s leading diversified developer across residential, retail and hospitality.', 'KA/RERA/PRES/005'),
('Lodha Group', '/images/experts/Lodha_Group.jpeg', 45, 175, 'Mumbai,Pune,Hyderabad', 'Mumbai-headquartered developer behind some of India\'s tallest luxury residences.', 'MH/RERA/LODH/006');

INSERT INTO properties (title, category, property_type, price, price_label, location_area, city, state, area_sqft, bedrooms, bathrooms, parking, possession_status, rera_number, builder_id, luxury_rating, description, amenities, hero_image, is_featured) VALUES
('Shivalik Sereno Villa', 'Residential', 'Villa', 24500000, ' 2.45 Crore', 'Bopal', 'Ahmedabad', 'Gujarat', 3250, 4, 4, 2, 'Ready To Move', 'GJ/RERA/P/001', 1, 4, 'Shivalik Sereno Villa is a villa in Bopal, Ahmedabad offering 3250 sq.ft. of thoughtfully designed living space, developed by Shivalik Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/1_1.jpeg', 1),
('Adani Shantigram Bungalow', 'Residential', 'Bungalow', 38500000, '3.85 Crore', 'Shantigram', 'Ahmedabad', 'Gujarat', 4100, 5, 5, 3, 'Ready To Move', 'GJ/RERA/P/002', 2, 4, 'Adani Shantigram Bungalow is a bungalow in Shantigram, Ahmedabad offering 4100 sq.ft. of thoughtfully designed living space, developed by Adani Realty.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/2_1.png', 1),
('Sindhu Heritage Tenament', 'Residential', 'Tenament', 9800000, ' 98 Lakh', 'Sindhu Bhavan Road', 'Ahmedabad', 'Gujarat', 1850, 3, 2, 1, 'Under Construction', 'GJ/RERA/P/003', 1, 3, 'Sindhu Heritage Tenament is a tenament in Sindhu Bhavan Road, Ahmedabad offering 1850 sq.ft. of thoughtfully designed living space, developed by Shivalik Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/3_1.jpeg', 0),
('Godrej Emerald Flat', 'Residential', 'Flat', 6200000, ' 62 Lakh', 'Wakad', 'Pune', 'Maharashtra', 1150, 2, 2, 1, 'Ready To Move', 'MH/RERA/P/004', 3, 3, 'Godrej Emerald Flat is a flat in Wakad, Pune offering 1150 sq.ft. of thoughtfully designed living space, developed by Godrej Properties.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/4_1.jpeg', 0),
('Lodha Park Apartment', 'Residential', 'Apartment', 18500000, '1.85 Crore', 'Lower Parel', 'Mumbai', 'Maharashtra', 1450, 3, 3, 1, 'New Launch', 'MH/RERA/P/005', 6, 4, 'Lodha Park Apartment is a apartment in Lower Parel, Mumbai offering 1450 sq.ft. of thoughtfully designed living space, developed by Lodha Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/5_1.jpeg', 1),
('Sobha Crystal Penthouse', 'Residential', 'Penthouse', 65000000, '  6.50 Crore', 'Whitefield', 'Bangalore', 'Karnataka', 5200, 4, 5, 3, 'Ready To Move', 'KA/RERA/P/006', 4, 5, 'Sobha Crystal Penthouse is a penthouse in Whitefield, Bangalore offering 5200 sq.ft. of thoughtfully designed living space, developed by Sobha Limited.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/6_1.jpeg', 1),
('Prestige Skyline Duplex', 'Residential', 'Duplex', 29500000, '  2.95 Crore', 'Sarjapur Road', 'Bangalore', 'Karnataka', 2900, 4, 4, 2, 'Under Construction', 'KA/RERA/P/007', 5, 4, 'Prestige Skyline Duplex is a duplex in Sarjapur Road, Bangalore offering 2900 sq.ft. of thoughtfully designed living space, developed by Prestige Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', '/images/experts/7_1.jpeg', 0),
('Adani Compact Studio', 'Residential', 'Studio Apartment', 3200000, '  32 Lakh', 'Gota', 'Ahmedabad', 'Gujarat', 480, 1, 1, 1, 'Ready To Move', 'GJ/RERA/P/008', 2, 2, 'Adani Compact Studio is a studio apartment in Gota, Ahmedabad offering 480 sq.ft. of thoughtfully designed living space, developed by Adani Realty.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden',  '/images/experts/8_1.jpeg', 0),
('Godrej Business Office', 'Commercial', 'Office', 14500000, '  1.45 Crore', 'Hinjewadi', 'Pune', 'Maharashtra', 2200, 0, 2, 4, 'Ready To Move', 'MH/RERA/P/009', 3, 3, 'Godrej Business Office is a office in Hinjewadi, Pune offering 2200 sq.ft. of thoughtfully designed living space, developed by Godrej Properties.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/9_1.jpeg', 0),
('Prestige High Street Retail', 'Commercial', 'Retail Shop', 21000000, '  2.10 Crore', 'Indiranagar', 'Bangalore', 'Karnataka', 1600, 0, 1, 0, 'Ready To Move', 'KA/RERA/P/010', 5, 3, 'Prestige High Street Retail is a retail shop in Indiranagar, Bangalore offering 1600 sq.ft. of thoughtfully designed living space, developed by Prestige Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/10_1.jpeg', 0),
('Lodha Auto Showroom', 'Commercial', 'Showroom', 48000000, '  4.80 Crore', 'Andheri East', 'Mumbai', 'Maharashtra', 5400, 0, 2, 6, 'Ready To Move', 'MH/RERA/P/011', 6, 3, 'Lodha Auto Showroom is a showroom in Andheri East, Mumbai offering 5400 sq.ft. of thoughtfully designed living space, developed by Lodha Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/11_1.jpeg', 0),
('Adani Logistics Warehouse', 'Commercial', 'Warehouse', 32000000, '  3.20 Crore', 'Sanand', 'Ahmedabad', 'Gujarat', 18000, 0, 1, 10, 'Ready To Move', 'GJ/RERA/P/012', 2, 2, 'Adani Logistics Warehouse is a warehouse in Sanand, Ahmedabad offering 18000 sq.ft. of thoughtfully designed living space, developed by Adani Realty.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/12_1.jpeg', 0),
('Sobha Co-working Hub', 'Commercial', 'Co-working Space', 9500000, '  95 Lakh', 'Sarjapur Road', 'Bangalore', 'Karnataka', 3100, 0, 4, 8, 'New Launch', 'KA/RERA/P/013', 4, 3, 'Sobha Co-working Hub is a co-working space in Sarjapur Road, Bangalore offering 3100 sq.ft. of thoughtfully designed living space, developed by Sobha Limited.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/13_1.jpeg', 0),
('Shivalik Riverside Farmhouse', 'Agricultural', 'Farmhouse', 18900000, '  1.89 Crore', 'Sanand Outskirts', 'Ahmedabad', 'Gujarat', 9000, 3, 2, 4, 'Ready To Move', 'GJ/RERA/P/014', 1, 3, 'Shivalik Riverside Farmhouse is a farmhouse in Sanand Outskirts, Ahmedabad offering 9000 sq.ft. of thoughtfully designed living space, developed by Shivalik Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/14_1.jpeg', 0),
('Lonavala Agricultural Plot', 'Agricultural', 'Agricultural Land', 4800000, '  48 Lakh', 'Lonavala', 'Pune', 'Maharashtra', 21780, 0, 0, 0, 'Ready To Move', 'MH/RERA/P/015', 3, 2, 'Lonavala Agricultural Plot is a agricultural land in Lonavala, Pune offering 21780 sq.ft. of thoughtfully designed living space, developed by Godrej Properties.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/15_1.jpeg', 0),
('Coorg Weekend Home', 'Agricultural', 'Weekend Home', 16500000, '  1.65 Crore', 'Coorg Hills', 'Bangalore', 'Karnataka', 4200, 3, 3, 2, 'Ready To Move', 'KA/RERA/P/016', 5, 3, 'Coorg Weekend Home is a weekend home in Coorg Hills, Bangalore offering 4200 sq.ft. of thoughtfully designed living space, developed by Prestige Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/16_1.jpeg', 0),
('Ambli Ultra Luxury Villa', 'Luxury', 'Ultra Luxury Villa', 95000000, '  9.50 Crore', 'Ambli', 'Ahmedabad', 'Gujarat', 7800, 5, 6, 4, 'Ready To Move', 'GJ/RERA/P/017', 1, 5, 'Ambli Ultra Luxury Villa is a ultra luxury villa in Ambli, Ahmedabad offering 7800 sq.ft. of thoughtfully designed living space, developed by Shivalik Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/17_1.jpeg', 1),
('Worli Sky Penthouse', 'Luxury', 'Luxury Penthouse', 185000000, '  18.50 Crore', 'Worli', 'Mumbai', 'Maharashtra', 6800, 4, 5, 4, 'Ready To Move', 'MH/RERA/P/018', 6, 5, 'Worli Sky Penthouse is a luxury penthouse in Worli, Mumbai offering 6800 sq.ft. of thoughtfully designed living space, developed by Lodha Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/18_1.jpeg', 1),
('Whitefield Golf Villa', 'Luxury', 'Golf Villa', 72000000, '  7.20 Crore', 'Whitefield', 'Bangalore', 'Karnataka', 5600, 4, 5, 3, 'Under Construction', 'KA/RERA/P/019', 4, 5, 'Whitefield Golf Villa is a golf villa in Whitefield, Bangalore offering 5600 sq.ft. of thoughtfully designed living space, developed by Sobha Limited.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/19_1.jpeg', 1),
('Goa Beach Villa Retreat', 'Luxury', 'Beach Villa', 110000000, '  11 Crore', 'Candolim', 'Mumbai', 'Maharashtra', 6200, 5, 6, 4, 'Ready To Move', 'MH/RERA/P/020', 6, 5, 'Goa Beach Villa Retreat is a beach villa in Candolim, Mumbai offering 6200 sq.ft. of thoughtfully designed living space, developed by Lodha Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/20_1.jpeg', 1),
('DLF Golf Course Residence', 'Luxury', 'Ultra Luxury Villa', 145000000, '  14.50 Crore', 'Golf Course Road', 'Delhi NCR', 'Haryana', 8200, 5, 6, 4, 'Ready To Move', 'HR/RERA/P/021', 3, 5, 'DLF Golf Course Residence is a ultra luxury villa in Golf Course Road, Delhi NCR offering 8200 sq.ft. of thoughtfully designed living space, developed by Godrej Properties.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/21_1.jpeg', 1),
('Jubilee Hills Smart Villa', 'Residential', 'Villa', 42500000, '  4.25 Crore', 'Jubilee Hills', 'Hyderabad', 'Telangana', 4400, 4, 4, 3, 'Ready To Move', 'TS/RERA/P/022', 5, 4, 'Jubilee Hills Smart Villa is a villa in Jubilee Hills, Hyderabad offering 4400 sq.ft. of thoughtfully designed living space, developed by Prestige Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/22_1.jpeg', 0),
('Vadodara Riverside Flat', 'Residential', 'Flat', 5400000, '  54 Lakh', 'Alkapuri', 'Vadodara', 'Gujarat', 1280, 2, 2, 1, 'Ready To Move', 'GJ/RERA/P/023', 1, 3, 'Vadodara Riverside Flat is a flat in Alkapuri, Vadodara offering 1280 sq.ft. of thoughtfully designed living space, developed by Shivalik Group.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/23_1.jpeg', 0),
('Rajkot Garden Bungalow', 'Residential', 'Bungalow', 11500000, '  1.15 Crore', 'Kalawad Road', 'Rajkot', 'Gujarat', 2600, 3, 3, 2, 'Ready To Move', 'GJ/RERA/P/024', 2, 3, 'Rajkot Garden Bungalow is a bungalow in Kalawad Road, Rajkot offering 2600 sq.ft. of thoughtfully designed living space, developed by Adani Realty.', 'Clubhouse,Swimming Pool,Gymnasium,24x7 Security,Power Backup,Landscaped Garden', ' /images/experts/24_1.jpeg', 0);

INSERT INTO property_images (property_id, image_url, tag) VALUES
(1, '/images/experts/1_1.jpeg', 'Hero'),
(1, '/images/experts/1_2.jpeg', 'Living Room'),
(1, '/images/experts/1_3.jpeg', 'Kitchen'),
(1, '/images/experts/1_4.jpeg', 'Bedroom'),
(1, '/images/experts/1_5.jpeg', 'Bathroom'),
(1, '/images/experts/1_6.jpeg', 'Exterior'),
(1, '/images/experts/1_7.jpeg', 'Amenities'),
(2, '/images/experts/2_1.png', 'Hero'),
(2, '/images/experts/2_2.png', 'Living Room'),
(2, '/images/experts/2_3.png', 'Kitchen'),
(2, '/images/experts/2_4.png', 'Bedroom'),
(2, '/images/experts/2_5.png', 'Bathroom'),
(2, '/images/experts/2_7.png', 'Exterior'),
(2, '/images/experts/2_6.png', 'Amenities'),
(3, '/images/experts/3_1.jpeg', 'Hero'),
(3, '/images/experts/3_2.jpeg', 'Living Room'),
(3, '/images/experts/3_3.jpeg', 'Kitchen'),
(3, '/images/experts/3_4.jpeg', 'Bedroom'),
(3, '/images/experts/3_5.jpeg', 'Bathroom'),
(3, '/images/experts/3_6.jpeg', 'Exterior'),
(3, '/images/experts/3_7.jpeg', 'Amenities'),
(4, '/images/experts/4_1.jpeg', 'Hero'),
(4, '/images/experts/4_2.jpeg', 'Living Room'),
(4, '/images/experts/4_3.jpeg', 'Kitchen'),
(4, '/images/experts/4_4.jpeg', 'Bedroom'),
(4, '/images/experts/4_5.jpeg', 'Bathroom'),
(4, '/images/experts/4_6.jpeg', 'Exterior'),
(4, '/images/experts/4_7.jpeg', 'Amenities'),
(5, '/images/experts/5_1.jpeg', 'Hero'),
(5, '/images/experts/5_2.jpeg', 'Living Room'),
(5, '/images/experts/5_3.jpeg', 'Kitchen'),
(5, '/images/experts/5_4.jpeg', 'Bedroom'),
(5, '/images/experts/5_5.jpeg', 'Bathroom'),
(5, '/images/experts/5_6.jpeg', 'Exterior'),
(5, '/images/experts/5_7.jpeg', 'Amenities'),
(6, '/images/experts/6_1.jpeg', 'Hero'),
(6, '/images/experts/6_2.jpeg', 'Living Room'),
(6, '/images/experts/6_3.jpeg', 'Kitchen'),
(6, '/images/experts/6_4.jpeg', 'Bedroom'),
(6, '/images/experts/6_5.jpeg', 'Bathroom'),
(6, '/images/experts/6_6.jpeg', 'Exterior'),
(6, '/images/experts/6_7.jpeg', 'Amenities'),
(7, '/images/experts/7_1.jpeg', 'Hero'),
(7, '/images/experts/7_2.jpeg', 'Living Room'),
(7, '/images/experts/7_3.jpeg', 'Kitchen'),
(7, '/images/experts/7_4.jpeg', 'Bedroom'),
(7, '/images/experts/7_5.jpeg', 'Bathroom'),
(7, '/images/experts/7_6.jpeg', 'Exterior'),
(7, '/images/experts/7_7.jpeg', 'Amenities'),
(8, '/images/experts/8_1.jpeg', 'Hero'),
(8, '/images/experts/8_2.jpeg', 'Living Room'),
(8, '/images/experts/8_3.jpeg', 'Kitchen'),
(8, '/images/experts/8_4.jpeg', 'Bedroom'),
(8, '/images/experts/8_5.jpeg', 'Bathroom'),
(8, '/images/experts/8_6.jpeg', 'Exterior'),
(8, '/images/experts/8_7.jpeg', 'Amenities'),
(9, '/images/experts/9_1.jpeg', 'Hero'),
(9, '/images/experts/9_2.jpeg', 'Living Room'),
(9, '/images/experts/9_3.jpeg', 'Kitchen'),
(9, '/images/experts/9_4.jpeg', 'Bedroom'),
(9, '/images/experts/9_5.jpeg', 'Bathroom'),
(9, '/images/experts/9_6.jpeg', 'Exterior'),
(9, '/images/experts/9_7.jpeg', 'Amenities'),
(10, '/images/experts/10_1.jpeg', 'Hero'),
(10, '/images/experts/10_2.jpeg', 'Living Room'),
(10, '/images/experts/10_3.jpeg', 'Kitchen'),
(10, '/images/experts/10_4.jpeg', 'Bedroom'),
(10, '/images/experts/10_5.jpeg', 'Bathroom'),
(10, '/images/experts/10_6.jpeg', 'Exterior'),
(10, '/images/experts/10_7.jpeg', 'Amenities'),
(11, '/images/experts/11_1.jpeg', 'Hero'),
(11, '/images/experts/11_2.jpeg', 'Living Room'),
(11, '/images/experts/11_3.jpeg', 'Kitchen'),
(11, '/images/experts/11_4.jpeg', 'Bedroom'),
(11, '/images/experts/11_5.jpeg', 'Bathroom'),
(11, '/images/experts/11_6.jpeg', 'Exterior'),
(11, '/images/experts/11_7.jpeg', 'Amenities'),
(12, '/images/experts/12_1.jpeg', 'Hero'),
(12, '/images/experts/12_2.jpeg', 'Living Room'),
(12, '/images/experts/12_3.jpeg', 'Kitchen'),
(12, '/images/experts/12_4.jpeg', 'Bedroom'),
(12, '/images/experts/12_5.jpeg', 'Bathroom'),
(12, '/images/experts/12_6.jpeg', 'Exterior'),
(12, '/images/experts/12_7.jpeg', 'Amenities'),
(13, '/images/experts/13_1.jpeg', 'Hero'),
(13, '/images/experts/13_2.jpeg', 'Living Room'),
(13, '/images/experts/13_3.jpeg', 'Kitchen'),
(13, '/images/experts/13_4.jpeg', 'Bedroom'),
(13, '/images/experts/13_5.jpeg', 'Bathroom'),
(13, '/images/experts/13_6.jpeg', 'Exterior'),
(13, '/images/experts/13_7.jpeg', 'Amenities'),
(14, '/images/experts/14_1.jpeg', 'Hero'),
(14, '/images/experts/14_2.jpeg', 'Living Room'),
(14, '/images/experts/14_3.jpeg', 'Kitchen'),
(14, '/images/experts/14_4.jpeg', 'Bedroom'),
(14, '/images/experts/14_5.jpeg', 'Bathroom'),
(14, '/images/experts/14_6.jpeg', 'Exterior'),
(14, '/images/experts/14_7.jpeg', 'Amenities'),
(15, '/images/experts/15_1.jpeg', 'Hero'),
(15, '/images/experts/15_2.jpeg', 'Living Room'),
(15, '/images/experts/15_3.jpeg', 'Kitchen'),
(15, '/images/experts/15_4.jpeg', 'Bedroom'),
(15, '/images/experts/15_5.jpeg', 'Bathroom'),
(15, '/images/experts/15_6.jpeg', 'Exterior'),
(15, '/images/experts/15_7.jpeg', 'Amenities'),
(16, '/images/experts/16_1.jpeg', 'Hero'),
(16, '/images/experts/16_2.jpeg', 'Living Room'),
(16, '/images/experts/16_3.jpeg', 'Kitchen'),
(16, '/images/experts/16_4.jpeg', 'Bedroom'),
(16, '/images/experts/16_5.jpeg', 'Bathroom'),
(16, '/images/experts/16_6.jpeg', 'Exterior'),
(16, '/images/experts/16_7.jpeg', 'Amenities'),
(17, '/images/experts/17_1.jpeg', 'Hero'),
(17, '/images/experts/17_2.jpeg', 'Living Room'),
(17, '/images/experts/17_3.jpeg', 'Kitchen'),
(17, '/images/experts/17_4.jpeg', 'Bedroom'),
(17, '/images/experts/17_5.jpeg', 'Bathroom'),
(17, '/images/experts/17_6.jpeg', 'Exterior'),
(17, '/images/experts/17_7.jpeg', 'Amenities'),
(18, '/images/experts/18_1.jpeg', 'Hero'),
(18, '/images/experts/18_2.jpeg', 'Living Room'),
(18, '/images/experts/18_3.jpeg', 'Kitchen'),
(18, '/images/experts/18_4.jpeg', 'Bedroom'),
(18, '/images/experts/18_5.jpeg', 'Bathroom'),
(18, '/images/experts/18_6.jpeg', 'Exterior'),
(18, '/images/experts/18_7.jpeg', 'Amenities'),
(19, '/images/experts/19_1.jpeg', 'Hero'),
(19, '/images/experts/19_2.jpeg', 'Living Room'),
(19, '/images/experts/19_3.jpeg', 'Kitchen'),
(19, '/images/experts/19_4.jpeg', 'Bedroom'),
(19, '/images/experts/19_5.jpeg', 'Bathroom'),
(19, '/images/experts/19_6.jpeg', 'Exterior'),
(19, '/images/experts/19_7.jpeg', 'Amenities'),
(20, '/images/experts/20_1.jpeg', 'Hero'),
(20, '/images/experts/20_2.jpeg', 'Living Room'),
(20, '/images/experts/20_3.jpeg', 'Kitchen'),
(20, '/images/experts/20_4.jpeg', 'Bedroom'),
(20, '/images/experts/20_5.jpeg', 'Bathroom'),
(20, '/images/experts/20_6.jpeg', 'Exterior'),
(20, '/images/experts/20_7.jpeg', 'Amenities'),
(21, '/images/experts/21_1.jpeg', 'Hero'),
(21, '/images/experts/21_2.jpeg', 'Living Room'),
(21, '/images/experts/21_3.jpeg', 'Kitchen'),
(21, '/images/experts/21_4.jpeg', 'Bedroom'),
(21, '/images/experts/21_5.jpeg', 'Bathroom'),
(21, '/images/experts/21_6.jpeg', 'Exterior'),
(21, '/images/experts/21_7.jpeg', 'Amenities'),
(22, '/images/experts/22_1.jpeg', 'Hero'),
(22, '/images/experts/22_2.jpeg', 'Living Room'),
(22, '/images/experts/22_3.jpeg', 'Kitchen'),
(22, '/images/experts/22_4.jpeg', 'Bedroom'),
(22, '/images/experts/22_5.jpeg', 'Bathroom'),
(22, '/images/experts/22_6.jpeg', 'Exterior'),
(22, '/images/experts/22_7.jpeg', 'Amenities'),
(23, '/images/experts/23_1.jpeg', 'Hero'),
(23, '/images/experts/23_2.jpeg', 'Living Room'),
(23, '/images/experts/23_3.jpeg', 'Kitchen'),
(23, '/images/experts/23_4.jpeg', 'Bedroom'),
(23, '/images/experts/23_5.jpeg', 'Bathroom'),
(23, '/images/experts/23_6.jpeg', 'Exterior'),
(23, '/images/experts/23_7.jpeg', 'Amenities'),
(24, '/images/experts/24_1.jpeg', 'Hero'),
(24, '/images/experts/24_2.jpeg', 'Living Room'),
(24, '/images/experts/24_3.jpeg', 'Kitchen'),
(24, '/images/experts/24_4.jpeg', 'Bedroom'),
(24, '/images/experts/24_5.jpeg', 'Bathroom'),
(24, '/images/experts/24_6.jpeg', 'Exterior'),
(24, '/images/experts/24_7.jpeg', 'Amenities');

INSERT INTO civil_engineers (name, photo_url, experience_years, projects_completed, specialization, city) VALUES
('Rakesh Patel', '/images/experts/Rakesh_Patel.jpeg', 18, 64, 'Structural Engineering, High-Rise Foundations', 'Ahmedabad'),
('Sunita Rao', '/images/experts/Sunita_Rao.jpeg', 14, 48, 'Seismic Design, RCC Structures', 'Mumbai'),
('Vikram Shah', '/images/experts/Vikram_Shah.jpeg', 22, 80, 'Soil Mechanics, Site Grading', 'Bangalore'),
('Anita Desai', '/images/experts/Anita_Desai.jpeg', 11, 35, 'MEP Coordination, Green Buildings', 'Pune');

INSERT INTO interior_designers (name, photo_url, experience_years, design_style, city) VALUES
('Scarlett Johansson', '/images/experts/Scarlett_Johansson.jpeg', 16, 'Contemporary Luxury', 'Mumbai'),
('Chris Evans', '/images/experts/Chris_Evans.jpeg', 10, 'Indo-Scandinavian', 'Bangalore'),
('Elizabeth Olsen', '/images/experts/Elizabeth_Olsen.jpeg', 13, 'Art Deco Revival', 'Ahmedabad'),
('Chris Hemswarth', '/images/experts/Chris_Hemswarth.jpeg', 9, 'Minimalist Zen', 'Delhi NCR');

INSERT INTO exterior_designers (name, photo_url, experience_years, specialty, city) VALUES
('Sushant Singh', '/images/experts/Sushant_Singh.jpeg', 15, 'Lighting & Landscape', 'Pune'),
('Wamiqa Gabbi', '/images/experts/Wamiqa_Gabbi.jpeg', 12, 'Sustainable Landscaping', 'Bangalore'),
('Rashmika', '/images/experts/Rashmika.jpeg', 19, 'Stone & Glass Facades', 'Ahmedabad');

INSERT INTO market_reports (city, index_name, growth_1yr_pct, growth_3yr_pct, growth_5yr_pct, growth_10yr_pct, rental_yield_pct, report_date) VALUES
('Ahmedabad', 'Ahmedabad Growth Index', 9.2, 28.5, 52.0, 145.0, 3.8, '2026-04-01'),
('Mumbai', 'Mumbai Luxury Index', 7.5, 24.0, 46.5, 128.0, 2.9, '2026-04-01'),
('Bangalore', 'Bangalore Rental Yield', 8.8, 27.2, 49.0, 132.0, 4.4, '2026-04-01'),
('Pune', 'Pune Appreciation Rate', 8.1, 25.8, 47.5, 121.0, 3.6, '2026-04-01'),
('Hyderabad', 'Hyderabad Momentum Index', 9.6, 30.1, 55.0, 150.0, 4.1, '2026-04-01'),
('Delhi NCR', 'Delhi NCR Prime Index', 7.0, 21.5, 41.0, 110.0, 2.6, '2026-04-01');

INSERT INTO testimonials (quote, author_name, author_title, sort_order) VALUES
('Real estate cannot be lost or stolen. Purchased wisely, it remains the safest investment.', 'Anonymous', 'Property Investor', 1),
('Owning a home is a cornerstone of wealth and financial security.', 'Anonymous', 'Homeowner', 2),
('The best investment on Earth is Earth.', 'Anonymous', 'NRI Investor', 3);

INSERT INTO ownership_journey (step_number, title, description, icon) VALUES
(1, 'Property Discovery', 'Explore curated listings and shortlist homes matched to your goals.', 'search'),
(2, 'Site Visit', 'Walk the property and neighbourhood with a dedicated relationship manager.', 'map-pin'),
(3, 'Documentation', 'Title verification, RERA checks and agreement drafting handled end-to-end.', 'file-text'),
(4, 'Loan Processing', 'Bank tie-ups help structure financing and disbursement timelines.', 'landmark'),
(5, 'Registration', 'Stamp duty, registration and handover formalities completed with our team.', 'stamp'),
(6, 'Possession', 'Keys handed over along with a full snag-check and orientation walkthrough.', 'key'),
(7, 'Wealth Creation', 'Ongoing portfolio tracking as your asset appreciates over the years.', 'trending-up');

INSERT INTO iconic_addresses (city, locality, image_url, blurb, avg_price_per_sqft) VALUES
('Ahmedabad', 'Sindhu Bhavan Road', ' ?text=Sindhu+Bhavan+Road&font=playfair-display', 'Ahmedabad premium boulevard of designer residences.', 9800),
('Ahmedabad', 'Ambli', ' ?text=Ambli&font=playfair-display', 'Gated luxury villas minutes from the riverfront.', 8600),
('Ahmedabad', 'Bopal', ' ?text=Bopal&font=playfair-display', 'Family-favoured suburb with strong rental demand.', 5200),
('Mumbai', 'Bandra West', ' ?text=Bandra+West&font=playfair-display', 'Iconic sea-facing lanes blending heritage and glamour.', 62000),
('Mumbai', 'Worli', ' ?text=Worli&font=playfair-display', 'Skyline addresses with the city tallest residences.', 58000),
('Mumbai', 'Juhu', ' ?text=Juhu&font=playfair-display', 'Beachside prestige with old-money pedigree.', 54000),
('Bangalore', 'Whitefield', ' ?text=Whitefield&font=playfair-display', 'Tech-corridor micro-market with consistent appreciation.', 9200),
('Bangalore', 'Sarjapur Road', ' ?text=Sarjapur+Road&font=playfair-display', 'Emerging luxury cluster near major IT campuses.', 8400),
('Delhi NCR', 'Golf Course Road', ' ?text=Golf+Course+Road&font=playfair-display', 'Gurugram flagship high-rise and villa address.', 16500),
('Delhi NCR', 'DLF Phase 5', ' ?text=DLF+Phase+5&font=playfair-display', 'Established premium enclave with mature infrastructure.', 15200);

INSERT INTO platform_stats (stat_key, stat_value, stat_label, sort_order) VALUES
('properties_listed', '5000+', 'Properties Listed', 1),
('happy_buyers', '2500+', 'Happy Buyers', 2),
('builders', '150+', 'Builders', 3),
('experts', '350+', 'Experts', 4),
('transactions', ' 5000+ Cr', 'Transactions Facilitated', 5),
('years_experience', '20+', 'Years Industry Experience', 6);
